name: CI/CD Pipeline
# currently continuous deployment pipeline only
on:
  push:
    branches: [ main ] # the workflow will be triggered when commit code is pushed to the main branch in the repository

jobs:
  continuous-deployment:
    runs-on: ubuntu-latest # the runner used in the workflow is ubuntu-latest (Ubuntu Linux OS)
    if: github.ref == 'refs/heads/main' # check if current branch is main 
    steps:
     # Step 1 - credentials for AWS user
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
     # Step 2 - final deployment, codedeploy is the application name on AWS and githubdeploy is the deployment group name on AWS
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name codedeploy \
            --deployment-group-name githubdeploy \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
